const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const axios = require('axios');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors());
app.use(bodyParser.json());

// Sample dashboard data
const generateDashboardData = () => {
  return {
    portfolioPerformance: [
      { month: 'Jan', returns: 2.4, benchmark: 1.8 },
      { month: 'Feb', returns: 1.9, benchmark: 2.3 },
      { month: 'Mar', returns: 3.2, benchmark: 2.5 },
      { month: 'Apr', returns: 2.8, benchmark: 2.1 },
      { month: 'May', returns: 3.5, benchmark: 2.7 },
      { month: 'Jun', returns: 3.0, benchmark: 2.9 },
    ],
    riskMetrics: [
      { category: 'Volatility', current: 12, threshold: 15 },
      { category: 'Value at Risk', current: 5.8, threshold: 8 },
      { category: 'Beta', current: 1.2, threshold: 1.5 },
      { category: 'Sharpe Ratio', current: 1.8, threshold: 1.5 },
    ],
    transactionVolume: [
      { day: 'Mon', count: 145, average: 120 },
      { day: 'Tue', count: 132, average: 122 },
      { day: 'Wed', count: 164, average: 125 },
      { day: 'Thu', count: 123, average: 118 },
      { day: 'Fri', count: 175, average: 130 },
    ],
    clientSegmentation: [
      { name: 'Retail', value: 45 },
      { name: 'HNW', value: 30 },
      { name: 'Institutional', value: 15 },
      { name: 'Corporate', value: 10 },
    ],
    keyMetrics: {
      aum: 1250000000,
      monthlyRevenue: 3500000,
      newClients: 45,
      clientRetention: 0.92,
      averageAccountSize: 750000,
      operatingMargin: 0.32
    }
  };
};

// API endpoint to get dashboard data
app.get('/api/dashboard-data', (req, res) => {
  // In a real app, you would fetch this from a database
  const dashboardData = generateDashboardData();
  res.json(dashboardData);
});

// API endpoint to get insights from dashboard data
app.post('/api/insights', (req, res) => {
  const { data } = req.body;
  
  // This would typically be generated by an AI model
  // Here we're hardcoding for the demo
  const insights = [
    "Portfolio is outperforming the benchmark by 0.7% on average",
    "Risk metrics are all within acceptable thresholds",
    "Transaction volume peaks on Fridays (35% higher than average)",
    "Retail clients represent the largest segment (45%) of the business"
  ];
  
  const recommendations = [
    "Consider reallocating 5% from fixed income to equities to capture market upside",
    "Monitor increasing volatility in technology sector",
    "Prepare for month-end reporting with focus on outperformance metrics",
    "Target HNW segment for growth with personalized offerings"
  ];
  
  res.json({ insights, recommendations });
});

// API endpoint to query Claude
app.post('/api/ask-claude', async (req, res) => {
  const { query, dashboardData } = req.body;
  
  try {
    // In production, this would call the Claude API
    // For demo purposes, we're simulating the response
    
    // Construct prompt for Claude
    const prompt = `
      You are a financial AI assistant helping interpret dashboard data.
      
      Here is the financial dashboard data:
      ${JSON.stringify(dashboardData, null, 2)}
      
      User query: ${query}
      
      Please provide a concise, helpful response based on the dashboard data. Include specific numbers and metrics when relevant.

    `;
    
    // Simulate Claude API call
    // In production, use the actual Claude API:
    console.log("PROMPT : ",prompt);
    const claudeResponse = await axios.post(
      'https://api.anthropic.com/v1/messages',
      {
        model: "claude-3-7-sonnet-20250219",
        max_tokens: 1000,
        messages: [
          { role: "user", content: prompt }
        ]
      },
      {
        headers: {
          'Content-Type': 'application/json',
          'anthropic-version': '2023-06-01',
          'x-api-key': process.env.CLAUDE_KEY
        }
      }
    );
    
    const response = claudeResponse.data.content[0].text;
    
    
    // Simulated Claude response based on query
    //let response = '';
    
    // if (query.toLowerCase().includes('performance')) {
    //   response = "The portfolio is consistently outperforming the benchmark across the last 6 months. In May, we saw the highest returns of 3.5% compared to the benchmark's 2.7%. Overall, the average outperformance is 0.7%, which is contributing positively to our risk-adjusted returns.";
    // } else if (query.toLowerCase().includes('risk')) {
    //   response = "All risk metrics are currently within acceptable thresholds. The volatility is at 12 against a threshold of 15, and the Value at Risk is 5.8 against a threshold of 8. Your Sharpe Ratio is particularly strong at 1.8, exceeding the threshold of 1.5, indicating good risk-adjusted returns.";
    // } else if (query.toLowerCase().includes('transaction') || query.toLowerCase().includes('volume')) {
    //   response = "Transaction volume shows a clear weekly pattern with Friday being the peak day (175 transactions), which is 35% higher than the average. This suggests clients are more active before weekends, which could be an opportunity for targeted engagement.";
    // } else if (query.toLowerCase().includes('client') || query.toLowerCase().includes('segment')) {
    //   response = "Retail clients represent your largest segment at 45%, followed by High Net Worth (HNW) at 30%. The Institutional segment (15%) and Corporate segment (10%) are smaller but typically have larger account sizes. Given your average account size of $750,000, you may want to focus growth strategies on the HNW segment.";
    // } else if (query.toLowerCase().includes('recommend') || query.toLowerCase().includes('suggest')) {
    //   response = "Based on the dashboard data, I recommend: 1) Capitalize on Friday's higher transaction volume by scheduling key announcements or offers, 2) Focus on growing the HNW segment which has potential for higher margins, 3) Highlight your strong risk-adjusted returns (Sharpe Ratio of 1.8) in client communications, and 4) Consider reallocating some assets to capture continued outperformance.";
    // } else {
    //   response = "Looking at your dashboard data, your financial metrics are generally positive. You're managing $1.25 billion in assets with a healthy operating margin of 32%. Your portfolio is outperforming benchmarks, and your risk metrics are within acceptable thresholds. Client retention is strong at 92%, though there may be opportunities to increase your average account size and further penetrate the HNW segment.";
    // }
    
    res.json({ response });
  } catch (error) {
    console.error('Error querying Claude:', error);
    res.status(500).json({ error: 'Failed to process query' });
  }
});

// Start server
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
